const data = {
    products: [
        {
            _id: '1',
            name: 'Aston Martin',
            category: 'Car',
            image: '/images/p1.jpg',
            price: 120000,
            brand: 'Aston Martin',
            Date: '10/10/2020',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt mattis sagittis. Vestibulum sit amet nibh a tortor condimentum',
        },
        {
            _id: '2',
            name: 'Audi',
            category: 'Car',
            image: '/images/p2.jpg',
            price: 100000,
            Date: '10/10/2020',
            brand: 'Audi',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt mattis sagittis. Vestibulum sit amet nibh a tortor condimentum',
        },
        {
            _id: '3',
            name: 'Chevrolet',
            category: 'Car',
            image: '/images/p3.jpg',
            price: 220000,
            Date: '10/10/2020',
            brand: 'Chevrolet',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt mattis sagittis. Vestibulum sit amet nibh a tortor condimentum',
        },
        {
            _id: '4',
            name: 'Datsun',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78000,
            brand: 'Datsun',
            Date: '10/10/2020',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt mattis sagittis. Vestibulum sit amet nibh a tortor condimentum',
        },
        {
            _id: '5',
            name: 'Ferrari',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65000,
            brand: 'Ferrari',
            Date: '10/10/2020',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt mattis sagittis. Vestibulum sit amet nibh a tortor condimentum',
        },
        {
            _id: '6',
            name: 'Ford',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 139000,
            brand: 'Ford',
            Date: '10/10/2020',
            description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tincidunt mattis sagittis. Vestibulum sit amet nibh a tortor condimentum',
        },
    ],
};
export default data;
